_target_: nuplan.planning.utils.multithreading.worker_parallel.SingleMachineParallelExecutor
_convert_: 'all'
use_process_pool: false  # If true, use ProcessPoolExecutor as the backend, otherwise uses ThreadPoolExecutor
max_workers: 4          # Limit to 4 workers to reduce thread pressure 